### PR TITLE
Updated Readme.txt with contact.

### PR DESCRIPTION
**Pull request by ghost**
Contacts numbers and mails are added

### CODE REVIEW

**Review by ThEArUnOdAyA — APPROVED** [review]
Ok reviewed and checked the code it's alright.

**Review by thegreywalker — APPROVED** [review]
All Seems fine ... Code is alright, Details are fine. Good Job, You've worked exactly and more than I wanted ... @himangshuishere  Good Job ... Merge the branch **_himangshuishere-patch- 1_**

**Comment by ghost** [comment]
Merged the pull request now!! @iamapurba2003

**Comment by thegreywalker** [comment]
Branch **_himangshuishere-patch- 1_** is removed 

@himangshuishere @TheArUnOdAyA

**Pull request merged**
